### PR TITLE
Configure bktec for each test runner

### PR DESCRIPTION
**Pull request by nprizal**
This repo is created to showcase basic config for each test runner supported by Buildkite Test Engine Client (bktec). I have pushed commits to the main branch to create a basic project for each test runner. This PR aimed to configure bktec for each test runner.

### CODE REVIEW

**Comment by niceking** [comment]
> This repo is created to showcase basic config

What links to this repo? Also the build pipeline is hidden right? So is your intent just that customers can view basic config? How come retry is configured by default in this basic example but not like include or exclude patterns?

**Comment by nprizal** [comment]
> What links to this repo? Also the build pipeline is hidden right? So is your intent just that customers can view basic config? 

Currently, there is none, but we can put a link to this repo from bktec README and/or docs. The intention **for now** is so customers can view basic config, while the pipeline remains hidden for internal verification. It will be good to have the pipeline public as well, so the customers can see it in action. However, that will require more works, which I don't think not our high priority for now.

> How come retry is configured by default in this basic example but not like include or exclude patterns?
Good point. In my opinion, the include/exclude patterns are less basic than retry/split by example. If we showcase include pattern, then we need to showcase exclude pattern, or combination of both. I'm happy to add that to this repo in a separate PR.

**Comment by niceking** [comment]
> we can put a link to this repo from bktec README and/or docs

Yeah I think we should do this from the README at the very least so we know that this exists, as its also our only internal e2e verification that bktec works for cypress and playwright. This repo and pipeline is handy and it would be good for it to be discoverable from other associated repos in Buildkite so we don't forget about it :) 

> Good point. In my opinion, the include/exclude patterns are less basic than retry/split by example. If we showcase include pattern, then we need to showcase exclude pattern, or combination of both. I'm happy to add that to this repo in a separate PR.

Hahaha my intention with this comment was actually the opposite of adding more examples to this repo, I was actually wondering if this repo should only show basic config, and we shouldn't configure the retry count 😂

**Review by niceking — APPROVED** [review]
LGTM, a follow up task to link to this setup from bktec repo, and can you also link the linear ticket to this PR?

**Comment by nprizal** [comment]
> aha my intention with this comment was actually the opposite of adding more examples to this repo, I was actually wondering if this repo should only show basic config, and we shouldn't configure the retry count 😂

Ah! Yeah, I think showing the very basic configuration is enough. I'll remove the retry and split by example.

**Pull request merged**
